# Generated by Django 3.2.16 on 2022-10-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='telephone_landline',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telephone_mobile',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
