# Generated by Django 3.2.16 on 2022-10-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20221008_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='telephone_landline',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
