# Generated by Django 3.2.16 on 2022-10-09 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(blank=True, max_length=35, null=True)),
                ('property_number', models.PositiveIntegerField()),
                ('street_name', models.CharField(blank=True, max_length=35, null=True)),
                ('locality', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=60)),
                ('postcode', models.CharField(max_length=8)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('image_hero', models.ImageField(blank=True, default='…/default_property_image_lwan0m', upload_to='images/')),
                ('floorplan', models.ImageField(blank=True, upload_to='images/')),
                ('epc', models.ImageField(blank=True, upload_to='images/')),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('detached', 'Detached'), ('semi-detached', 'Semi-detached'), ('terraced', 'Terraced'), ('end terrace', 'End Terrace'), ('cottage', 'Cottage'), ('bungalows', 'Bungalows')], max_length=13)),
                ('tenure', models.CharField(blank=True, choices=[('', "I don't know"), ('freehold', 'Freehold'), ('shared freehold', 'Shared freehold'), ('leasehold', 'Leasehold'), ('commonhold', 'Commonhold'), ('shared ownership', 'Shared ownership')], max_length=16)),
                ('council_tax_band', models.CharField(blank=True, choices=[('', "I don't know"), ('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E'), ('f', 'F'), ('g', 'G'), ('h', 'H')], max_length=1)),
                ('num_bedrooms', models.PositiveIntegerField()),
                ('num_bathrooms', models.PositiveIntegerField()),
                ('has_garden', models.BooleanField(default=False)),
                ('has_parking', models.BooleanField(default=False)),
                ('is_sold_stc', models.BooleanField(default=False)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
