# Generated by Django 3.2.16 on 2022-10-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='street_name',
            field=models.CharField(default='', max_length=35),
            preserve_default=False,
        ),
    ]
