# Generated by Django 3.2.16 on 2022-10-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertys', '0002_auto_20221009_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image_hero',
            field=models.ImageField(blank=True, default='../default_property_image_lwan0m.jpg', upload_to='images/'),
        ),
    ]
